#!/usr/bin/env python3
# source .venv/bin/activate
"""
NFL Route Tracker - Frame Extraction Script for Manual Labeling
=================================================================

This script extracts frames from NFL All-22 videos for manual labeling using LabelImg.
"""

# pip install opencv-python labelImg

import cv2
import argparse
from pathlib import Path
#from tqdm import tqdm
import sys


def extract_frames(video_path: str, output_dir: str, every_n_frames: int = 10, max_frames: int = 500):
    """
    Extract frames from a video for manual labeling.
    """
    video_path = Path(video_path)
    output_dir = Path(output_dir)

    if not video_path.exists():
        print(f"ERROR: Video file not found: {video_path}")
        sys.exit(1)

    # Create output directory structure
    video_name = video_path.stem
    frames_dir = output_dir / video_name
    frames_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n{'='*60}")
    print(f"FRAME EXTRACTION FOR MANUAL LABELING")
    print(f"{'='*60}")
    print(f"Video: {video_path}")
    print(f"Output: {frames_dir}")
    print(f"Extracting every {every_n_frames} frames (max {max_frames} frames)")
    print()

    # Open video
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        print(f"ERROR: Could not open video: {video_path}")
        sys.exit(1)

    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    fps = cap.get(cv2.CAP_PROP_FPS)
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    print(f"Video properties: {width}x{height} @ {fps:.2f}fps, {total_frames} total frames")
    print()

    # Calculate how many frames we'll extract
    frames_to_extract = min(total_frames // every_n_frames, max_frames)
    print(f"Will extract approximately {frames_to_extract} frames")
    print()

    extracted_count = 0

    for frame_idx in range(0, total_frames, every_n_frames):
        if extracted_count >= max_frames:
            break

        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)
        ret, frame = cap.read()

        if not ret:
            break

        # Save frame
        output_filename = f"frame_{frame_idx:06d}.jpg"
        output_path = frames_dir / output_filename
        cv2.imwrite(str(output_path), frame, [cv2.IMWRITE_JPEG_QUALITY, 95])

        extracted_count += 1

        if extracted_count % 10 == 0:
            print(f"  Extracted {extracted_count} frames...")

    cap.release()

    print(f"\n Successfully extracted {extracted_count} frames to:")
    print(f"  {frames_dir}")

    # Create class definitions file
    classes_file = output_dir / "classes.txt"
    with open(classes_file, 'w') as f:
        f.write("player\n")
    print(f"\n✓ Created class definitions: {classes_file}")
    print(f"  Content: player")

    # NEXT STEPS
    # 1) install and launch labelImg
    # 2) open directory based on frames_dir, edit predefined class
    # 3) draw boxes around players for each frame and save
    # 4) save annotations into YOLO .txt format

    return frames_dir


# used later to combine all trained frames into one file
def setup_yolo_dataset(frames_dir: Path, dataset_yaml_path: Path = None):
    """
    Set up the YOLO dataset structure for training.

    Creates:
        - images/train/
        - images/val/
        - labels/train/
        - labels/val/
        - dataset.yaml
    """
    dataset_dir = frames_dir.parent / "yolo_dataset"
    dataset_dir.mkdir(exist_ok=True)

    for split in ['train', 'val']:
        (dataset_dir / 'images' / split).mkdir(parents=True, exist_ok=True)
        (dataset_dir / 'labels' / split).mkdir(parents=True, exist_ok=True)

    # Move all labeled frames and annotations to train
    for frame_file in frames_dir.glob("frame_*.jpg"):
        # Copy image to train
        import shutil
        shutil.copy(frame_file, dataset_dir / 'images' / 'train' / frame_file.name)

        # Copy corresponding label if exists
        label_file = frame_file.with_suffix('.txt')
        if label_file.exists():
            shutil.copy(label_file, dataset_dir / 'labels' / 'train' / label_file.name)

    # Create dataset.yaml
    if dataset_yaml_path is None:
        dataset_yaml_path = dataset_dir / 'dataset.yaml'

    yaml_content = f"""# NFL All-22 Player Detection Dataset
                        # Generated by extract_frames.py

                        path: {dataset_dir.absolute()}
                        train: images/train
                        val: images/val

                        # Classes
                        names:
                        0: player

                        # Number of classes
                        nc: 1"""
    with open(dataset_yaml_path, 'w') as f:
        f.write(yaml_content)

    print(f"\n Created YOLO dataset structure at: {dataset_yaml_path.parent}")
    print(f"  Dataset YAML: {dataset_yaml_path}")

    return dataset_yaml_path

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Extract frames from NFL All-22 videos for manual labeling",
                                    formatter_class=argparse.RawDescriptionHelpFormatter,
                                    epilog=__doc__)
    parser.add_argument('--video', '-v', type=str, default=None, help='Path to video file (default: first .mp4 in data/video_test/)')
    parser.add_argument('--output', '-o', type=str, default='training_data', help='Output directory for extracted frames (default: training_data)')
    parser.add_argument('--every', '-e', type=int, default=10, help='Extract every N frames (default: 10)')
    parser.add_argument('--max', '-m', type=int, default=500, help='Maximum frames to extract (default: 500)')

    args = parser.parse_args()

    # Find video if not specified
    if args.video is None:
        # Try to find first video in data/video_test/
        default_video = Path(__file__).parent.parent / "data" / "video_test"
        videos = list(default_video.glob("*.mp4"))
        if videos:
            args.video = str(videos[0])
            print(f"Using video: {args.video}")
        else:
            print("ERROR: No video specified and no videos found in data/video_test/")
            print("Please specify a video path with --video")
            sys.exit(1)

    # Run extraction
    output_dir = Path(args.output)
    extract_frames(video_path=args.video, output_dir=output_dir, every_n_frames=args.every, max_frames=args.max)