#!/usr/bin/env python3
"""
NFL Route Tracker - YOLO Fine-Tuning Setup Script
==================================================

This script sets up the complete YOLO fine-tuning workflow for NFL All-22 player detection.
"""

import argparse
import sys
from pathlib import Path
import shutil
import random


def scan_labeled_videos(data_dir: Path):
    """
    Scan all video folders and collect all labeled frames.
    Returns a list of (video_folder, frame_path, label_path) tuples.
    """
    labeled_frames = []

    if not data_dir.exists():
        return labeled_frames

    # Find all video folders (folders containing frame_*.jpg files)
    for video_folder in data_dir.iterdir():
        if not video_folder.is_dir():
            continue

        # Find all frame images
        frame_files = sorted(video_folder.glob("frame_*.jpg"))

        for frame_path in frame_files:
            # Corresponding label file
            label_path = frame_path.with_suffix('.txt')

            if label_path.exists():
                labeled_frames.append((video_folder.name, frame_path, label_path))
            else:
                print(f"  WARNING: No label for {frame_path.name} in {video_folder.name}")

    return labeled_frames


def create_yolo_dataset_structure(labeled_frames: list, output_dir: Path, train_split: float = 0.8):
    """
    Create the proper YOLO dataset structure.

    Structure:
        output_dir/
            dataset.yaml
            images/
                train/
                val/
            labels/
                train/
                val/
    """
    # Create directories
    images_train = output_dir / 'images' / 'train'
    images_val = output_dir / 'images' / 'val'
    labels_train = output_dir / 'labels' / 'train'
    labels_val = output_dir / 'labels' / 'val'

    for dir_path in [images_train, images_val, labels_train, labels_val]:
        dir_path.mkdir(parents=True, exist_ok=True)

    # Shuffle and split
    random.shuffle(labeled_frames)
    split_idx = int(len(labeled_frames) * train_split)
    train_frames = labeled_frames[:split_idx]
    val_frames = labeled_frames[split_idx:]

    print(f"\nSplitting {len(labeled_frames)} frames:")
    print(f"  Training: {len(train_frames)} frames")
    print(f"  Validation: {len(val_frames)} frames")

    # Copy training files
    for video_name, frame_path, label_path in train_frames:
        # Unique filename to avoid collisions
        new_name = f"{video_name}_{frame_path.name}"
        shutil.copy(frame_path, images_train / new_name)
        shutil.copy(label_path, labels_train / new_name.replace('.jpg', '.txt'))

    # Copy validation files
    for video_name, frame_path, label_path in val_frames:
        new_name = f"{video_name}_{frame_path.name}"
        shutil.copy(frame_path, images_val / new_name)
        shutil.copy(label_path, labels_val / new_name.replace('.jpg', '.txt'))

    return len(train_frames), len(val_frames)


def create_dataset_yaml(output_dir: Path, num_train: int, num_val: int):
    """
    Create the dataset.yaml file for YOLO training.
    """
    yaml_content = f"""# NFL All-22 Player Detection Dataset
# Generated by prepare_training.py
# Training frames: {num_train}, Validation frames: {num_val}

# Dataset root path (absolute path recommended)
path: /content/drive/MyDrive/NFL_Route_Tracker/yolo_dataset

# Training and validation image directories
train: images/train
val: images/val

# Class names (YOLO format - index starts at 0)
names:
  0: player

# Number of classes
nc: 1

# Image size (multiple of 32)
imgsz: 960
"""
    yaml_path = output_dir / 'dataset.yaml'
    with open(yaml_path, 'w') as f:
        f.write(yaml_content)
    print(f"\n✓ Created dataset.yaml at: {yaml_path}")
    return yaml_path


def create_training_script(dataset_yaml: Path, model_name: str = 'yolov8l.pt'):
    """
    Create a shell script for training.
    """
    script_content = f"""#!/bin/bash
# NFL YOLO Fine-Tuning Training Script
# ======================================
# Run this script to train the model

# Activate your virtual environment if needed
# source venv/bin/activate

# Training command
yolo detect train \\
    data="{dataset_yaml}" \\
    model="{model_name}" \\
    epochs=50 \\
    imgsz=960 \\
    batch=4 \\
    patience=10 \\
    save=True \\
    save_period=10 \\
    device=0 \\
    workers=8 \\
    project=runs/train \\
    name=nfl_players \\
    exist_ok=True \\
    pretrained=True \\
    optimizer=AdamW \\
    lr0=0.001 \\
    lrf=0.01 \\
    momentum=0.937 \\
    weight_decay=0.0005 \\
    warmup_epochs=3.0 \\
    warmup_momentum=0.8 \\
    warmup_bias_lr=0.1 \\
    box=7.5 \\
    cls=0.5 \\
    dfl=1.5 \\
    close_mosaic=10 \\
    amp=True \\
    fraction=1.0 \\
    profile=False \\
    overlap=True \\
    multi_scale=False \\
    single_cls=True

echo ""
echo "Training complete! Model saved to runs/train/nfl_players/"
echo "To use the trained model, update config.py:"
echo '  model_name = "runs/train/nfl_players/weights/best.pt"'
"""
    script_path = dataset_yaml.parent / "train.sh"
    with open(script_path, 'w') as f:
        f.write(script_content)
    print(f"✓ Created training script: {script_path}")
    import os
    os.chmod(script_path, 0o755)
    return script_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Prepare YOLO dataset from labeled NFL All-22 frames",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )

    parser.add_argument(
        '--data-dir', '-d',
        type=str,
        default='training_data',
        help='Path to training_data directory containing video folders (default: training_data)'
    )

    parser.add_argument(
        '--output', '-o',
        type=str,
        default='yolo_dataset',
        help='Output directory for YOLO dataset structure (default: yolo_dataset)'
    )

    parser.add_argument(
        '--split', '-s',
        type=float,
        default=0.8,
        help='Training/validation split ratio (default: 0.8 = 80%% train)'
    )

    parser.add_argument(
        '--model', '-m',
        type=str,
        default='yolov8l.pt',
        help='Base YOLO model to fine-tune (default: yolov8l.pt)'
    )

    args = parser.parse_args()

    data_dir = Path(args.data_dir)
    output_dir = Path(args.output)

    if not data_dir.exists():
        print(f"ERROR: Training data directory not found: {data_dir}")
        print("\nPlease ensure you have:")
        print("  training_data/")
        print("    test6/")
        print("      frame_000000.jpg")
        print("      frame_000000.txt")
        print("      ...")
        print("    test7/")
        print("      ...")
        print("\nOr specify the correct path with --data-dir")
        sys.exit(1)

    print(f"\n{'='*60}")
    print(f"YOLO TRAINING SETUP")
    print(f"{'='*60}")
    print(f"\nScanning for labeled frames in: {data_dir}")

    # Scan all labeled frames
    labeled_frames = scan_labeled_videos(data_dir)

    if len(labeled_frames) == 0:
        print(f"\nERROR: No labeled frames found!")
        print("Please ensure your video folders contain both .jpg and .txt files.")
        sys.exit(1)

    # Group by video folder
    video_counts = {}
    for video_name, frame_path, label_path in labeled_frames:
        video_counts[video_name] = video_counts.get(video_name, 0) + 1

    print(f"\nFound {len(labeled_frames)} labeled frames from {len(video_counts)} videos:")
    for video_name, count in sorted(video_counts.items()):
        print(f"  {video_name}: {count} frames")

    # Create YOLO dataset structure
    print(f"\nCreating YOLO dataset structure in: {output_dir}")
    print(f"Train/val split: {args.split:.0%} / {(1-args.split):.0%}")

    num_train, num_val = create_yolo_dataset_structure(labeled_frames, output_dir, train_split=args.split)

    # Create dataset.yaml
    dataset_yaml = create_dataset_yaml(output_dir, num_train, num_val)

    # Create training script
    create_training_script(dataset_yaml, args.model)